### ISSUE TITLE
Feature request: Allow icon image size

### ISSUE THREAD

**Issue by Toflar** [cferdinandi/jellyfish#19]
Hi,

I use jellyfish in a lot of different circumstances and a lot of different file sizes. For that use case I use an `.svg` loading image so it doesn't look blurred for big images (BTW: I think you should go for an `.svg` default instead of a `.gif` as well ;-)). However, depending on the image size I would like to have the loading icon size to be different. For smaller images, say, 100 x 100 pixels it probably makes sense to have the loading image 80 x 80 pixels. For bigger images like 800 x 600 pixels, a loading spinner as big as 600 pixels is probably just too big and 80 x 80 too small :-)

However, I'm not sure if we want to provide exact pixel value settings so that it generates `<img src="" width="80" height="80">` or have something more flexible with percentages or so? What do you think?

**Comment by cferdinandi** [comment]
@Toflar When I think about a typical use case for lazy loaded images, I'm not sure I see a need for loaders of different sizes. In fact, that's the opposite of what I typically see in the real world (I do see gray placeholder boxes for images that are the same size as the eventual images, with loaders floating there, though).

SVGs would be great, but they're not supported everywhere, and that adds another test to run before loading. Plus not everyone uses SVG, so that needs to be an option, which adds more complexity to the script.

Don't get me wrong: these are all great ideas. But this is a low use script that I don't have much time to commit to, so I prefer to keep it low maintenance.
